In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
mth161 = pd.read_excel('C:/Users/mjc341/desktop/TESTPY/MTH161.xlsx')

In [4]:
mth161.head(5)

     APP_ID  ALEKS AP  IB COURSE Credit  ACT MTH  SAT-MSS (NEW)  SAT_MTH (NEW)
0  50432885     89  0   0             0        0              0              0
1  50457667     84  0   0             0        0              0              0
2  50475188      0  0   0       MTH 101        0              0            600
3  50480064     63  0   0             0        0              0              0
4  50480105     65  0   0       MTH 101        0              0              0

In [6]:
mth161.dtypes

APP_ID            int64
ALEKS             int64
AP               object
IB                int64
COURSE Credit    object
ACT MTH           int64
SAT-MSS (NEW)     int64
SAT_MTH (NEW)     int64
dtype: object

In [7]:
mth161.columns

Index(['APP_ID', 'ALEKS', 'AP', 'IB', 'COURSE Credit', 'ACT MTH',
       'SAT-MSS (NEW)', 'SAT_MTH (NEW)'],
      dtype='object')

In [8]:
mth161.rename (columns= {'APP_ID':'ID', 'ALEKS':'ALKS', 'COURSE Credit':'COURSE', 'ACT MTH':'ACT',
       'SAT-MSS (NEW)':'MSS', 'SAT_MTH (NEW)':'MTH'})

            ID  ALKS     AP  IB   COURSE  ACT  MSS  MTH
0     50432885    89      0   0        0    0    0    0
1     50457667    84      0   0        0    0    0    0
2     50475188     0      0   0  MTH 101    0    0  600
3     50480064    63      0   0        0    0    0    0
4     50480105    65      0   0  MTH 101    0    0    0
5     50480115    73      0   0        0    0    0    0
6     50480127    65      0   0        0    0    0    0
7     54000209    81      0   0        0    0    0    0
8     54000751    90  MAB 5   0        0    0    0    0
9     53673491    55      0   0        0    0    0    0
10    54001161    67      0   0        0    0    0    0
11    54005970    87      0   0  MTH 101    0    0    0
12    53762062    79      0   0        0    0    0    0
13    54006062    81      0   0        0    0    0    0
14    54006147    81      0   0        0    0    0    0
15    54006778    84      0   0        0    0    0    0
16    54006818    60      0   0        0    0    0    0
17    54006843    61      0   0        0    0    0    0
18    54006758    83      0   0        0    0    0    0
19    54006018    84      0   0        0    0    0    0
20    54006183     0      0   0        0    0    0    0
21    53803707    80      0   0        0    0    0    0
22    53479912    80      0   0        0    0    0    0
23    54006795    65      0   0        0    0    0    0
24    53786223    56      0   0        0    0    0    0
25    54007209    68      0   0        0    0    0    0
26    54007179    42      0   0        0    0    0    0
27    54007326    62      0   0        0    0    0    0
28    54007773    84      0   0        0    0    0    0
29    54007837    93      0   0        0    0    0    0
...        ...   ...    ...  ..      ...  ...  ...  ...
1761  54043655    44      0   0  MTH 101   26    0    0
1762  54261739     0      0   0  MTH 130    0    0  740
1763  54010100    93      0   0  MTH 101    0    0  600
1764  54163643    92      0   0   MTH 99    0    0  440
1765  54261801    97      0   0  MTH 130   25    0    0
1766  54261802    39      0   0   MTH 99    0    0    0
1767  54182738     0      0   0  MTH 140    0    0  620
1768  54183895     0      0   0  MTH 161    0    0  710
1769  54262023    95      0   0  MTH 101    0    0    0
1770  54262026     0      0   0  MTH 108    0    0  710
1771  54021258    80      0   0        0    0    0    0
1772  54261881    61      0   0  MTH 130    0    0    0
1773  54261995    39      0   0        0    0    0    0
1774  54188097    60      0   0        0    0    0    0
1775  54176105    85      0   0        0    0    0    0
1776  54148720     0      0   0  MTH 130    0    0  760
1777  54263076    92      0   0  MTH 130    0    0    0
1778  54263195    82      0   0        0    0    0    0
1779  54152799    82      0   0        0    0    0    0
1780  54184809    94      0   0        0    0    0    0
1781  54264670    67      0   0   MTH 99    0    0    0
1782  54264771     0      0   0  MTH 161    0    0  700
1783  54154290     0      0   0  MTH 161    0    0  790
1784  54240616    80      0   0        0    0    0    0
1785  54265682     0      0   0   MTH 99    0    0  520
1786  54265633    92      0   0  MTH 101    0    0    0
1787  54265636    94      0   0  MTH 101    0    0    0
1788  54022824    64      0   0        0   22    0  590
1789  54158287    41      0   0        0    0    0    0
1790  50417166     0      0   0  MTH 161    0    0    0

[1791 rows x 8 columns]

In [17]:
MTH_LEVEL = []

In [19]:
for row in mth161['ALEKS']:
    if row >55:
        MTH_LEVEL.append ('yes')
    else:
        MTH_LEVEL.append('no')

In [20]:
mth161.head(10)

,APP_ID,ALEKS,AP,IB,COURSE Credit,ACT MTH,SAT-MSS (NEW),SAT_MTH (NEW)
0,50432885,89,0,0,0,0,0,0
1,50457667,84,0,0,0,0,0,0
2,50475188,0,0,0,MTH 101,0,0,600
3,50480064,63,0,0,0,0,0,0
4,50480105,65,0,0,MTH 101,0,0,0
5,50480115,73,0,0,0,0,0,0
6,50480127,65,0,0,0,0,0,0
7,54000209,81,0,0,0,0,0,0
8,54000751,90,MAB 5,0,0,0,0,0
9,53673491,55,0,0,0,0,0,0

In [21]:
mth161['MTH_LEVEL'] = MTH_LEVEL

In [22]:
mth161.head(10)

,APP_ID,ALEKS,AP,IB,COURSE Credit,ACT MTH,SAT-MSS (NEW),SAT_MTH (NEW),MTH_LEVEL
0,50432885,89,0,0,0,0,0,0,yes
1,50457667,84,0,0,0,0,0,0,yes
2,50475188,0,0,0,MTH 101,0,0,600,no
3,50480064,63,0,0,0,0,0,0,yes
4,50480105,65,0,0,MTH 101,0,0,0,yes
5,50480115,73,0,0,0,0,0,0,yes
6,50480127,65,0,0,0,0,0,0,yes
7,54000209,81,0,0,0,0,0,0,yes
8,54000751,90,MAB 5,0,0,0,0,0,yes
9,53673491,55,0,0,0,0,0,0,no

In [23]:
mth161=mth161.rename (columns= {'APP_ID':'ID', 'ALEKS':'ALKS', 'COURSE Credit':'COURSE', 'ACT MTH':'ACT',
       'SAT-MSS (NEW)':'MSS', 'SAT_MTH (NEW)':'MTH'})

In [24]:
mth161.head(4)

         ID  ALKS AP  IB   COURSE  ACT  MSS  MTH MTH_LEVEL
0  50432885    89  0   0        0    0    0    0       yes
1  50457667    84  0   0        0    0    0    0       yes
2  50475188     0  0   0  MTH 101    0    0  600        no
3  50480064    63  0   0        0    0    0    0       yes

In [25]:
for row in mth161['ALKS']:
    if row >55:
        MTH_LEVEL.append ('yes')
    else:
        MTH_LEVEL.append('no')

In [27]:
len('ALKS')

4

In [28]:
len('MTH_LEVEL')

9

In [29]:
len(mth161['ALKS'])

1791

In [30]:
len(mth161['MTH_LEVEL'])

1791

In [31]:
del (mth161['MTH_LEVEL'])

In [32]:
mth161.head(2)

         ID  ALKS AP  IB COURSE  ACT  MSS  MTH
0  50432885    89  0   0      0    0    0    0
1  50457667    84  0   0      0    0    0    0

In [50]:
for row in mth161['ALKS']:
    if row <55:
        MTH_LEVEL.append ('Algebra')
    elif row >=55:
        MTH_LEVEL.append('pre-calc')
    elif row >=65:
        MTH_LEVEL.append ('pre-calc 130,108,140')
    elif row >=75:
        MTH_LEVEL.append('MTH161 ready')
    else:
        MTH_LEVEL.append('error')

In [53]:
len(MTH_LEVEL)

5373

In [54]:
MTH_LEVEL

['yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 ...]

In [55]:
ALEKS_MTH_LEVEL = []

In [56]:
for row in mth161['ALKS']:
    if row <55:
        ALEKS_MTH_LEVEL.append ('Algebra')
    elif row >=55:
        ALEKS_MTH_LEVEL.append('pre-calc')
    elif row >=65:
        ALEKS_MTH_LEVEL.append ('pre-calc 130,108,140')
    elif row >=75:
        ALEKS_MTH_LEVEL.append('MTH161 ready')
    else:
        ALEKS_MTH_LEVEL.append('error')

In [57]:
mth161['ALEKS_MTH_LEVEL'] = ALEKS_MTH_LEVEL

In [59]:
mth161.head(15)

          ID  ALKS     AP  IB   COURSE  ACT  MSS  MTH ALEKS_MTH_LEVEL
0   50432885    89      0   0        0    0    0    0        pre-calc
1   50457667    84      0   0        0    0    0    0        pre-calc
2   50475188     0      0   0  MTH 101    0    0  600         Algebra
3   50480064    63      0   0        0    0    0    0        pre-calc
4   50480105    65      0   0  MTH 101    0    0    0        pre-calc
5   50480115    73      0   0        0    0    0    0        pre-calc
6   50480127    65      0   0        0    0    0    0        pre-calc
7   54000209    81      0   0        0    0    0    0        pre-calc
8   54000751    90  MAB 5   0        0    0    0    0        pre-calc
9   53673491    55      0   0        0    0    0    0        pre-calc
10  54001161    67      0   0        0    0    0    0        pre-calc
11  54005970    87      0   0  MTH 101    0    0    0        pre-calc
12  53762062    79      0   0        0    0    0    0        pre-calc
13  54006062    81      0   0        0    0    0    0        pre-calc
14  54006147    81      0   0        0    0    0    0        pre-calc

In [60]:
for row in mth161['ALKS']:
    if row <55:
        MTH_LEVEL.append ('Algebra')
    elif row >=55 and row <65:
        MTH_LEVEL.append('pre-calc')
    elif row >=65 and row <75:
        MTH_LEVEL.append ('pre-calc 130,108,140')
    elif row >=75:
        MTH_LEVEL.append('MTH161 ready')
    else:
        MTH_LEVEL.append('error')

In [61]:
ALKS_MTH_LEVEL = []

In [62]:
for row in mth161['ALKS']:
    if row <55:
        ALKS_MTH_LEVEL.append ('Algebra')
    elif row >=55 and row <65:
        ALKS_MTH_LEVEL.append('pre-calc')
    elif row >=65 and row <75:
        ALKS_MTH_LEVEL.append ('pre-calc 130,108,140')
    elif row >=75:
        ALKS_MTH_LEVEL.append('MTH161 ready')
    else:
        ALKS_MTH_LEVEL.append('error')

In [64]:
len(ALKS_MTH_LEVEL)

1791

In [66]:
ALKS_MTH_LEVEL

['MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'Algebra',
 'pre-calc',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 ...]

In [67]:
mth161['ALKS_MTH_LEVEL'] = ALKS_MTH_LEVEL

In [69]:
del mth161['ALEKS_MTH_LEVEL']
mth161.head(5)

         ID  ALKS AP  IB   COURSE  ACT  MSS  MTH        ALKS_MTH_LEVEL
0  50432885    89  0   0        0    0    0    0          MTH161 ready
1  50457667    84  0   0        0    0    0    0          MTH161 ready
2  50475188     0  0   0  MTH 101    0    0  600               Algebra
3  50480064    63  0   0        0    0    0    0              pre-calc
4  50480105    65  0   0  MTH 101    0    0    0  pre-calc 130,108,140

In [70]:
AP_MTH_LEVEL = []

In [71]:
for row in mth161['AP']:
    if row == "MAB 3":
        AP_MTH_LEVEL.append ('pre-calc 130,108,140')
    elif row == 'MAB 4 ' or row == 'MAB 5':
        AP_MTH_LEVEL.append ('MTH161 ready')
    elif row == 'MBC 4' or row == 'MBC 5' or row == 'MBC 6':
        AP_MTH_LEVEL.append ('MTH161 ready')
    else:
        AP_MTH_LEVEL.append('error')

In [73]:
len (AP_MTH_LEVEL)

1791

In [74]:
mth161['AP_MTH_LEVEL'] = AP_MTH_LEVEL

In [75]:
mth161.head(5)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,AP_MTH_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,error
1,50457667,84,0,0,0,0,0,0,MTH161 ready,error
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,error
3,50480064,63,0,0,0,0,0,0,pre-calc,error
4,50480105,65,0,0,MTH 101,0,0,0,"pre-calc 130,108,140",error

In [76]:
AP_MTH_LEVEL

['error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'error',
 'MTH161 ready',
 'error',
 'error',
 'error',
 ...]

In [77]:
IB_MTH_LEVEL = []

In [80]:
for row in mth161['IB']:
    if row >= 4:
        IB_MTH_LEVEL.append ('MTH161 ready')
    else:
        IB_MTH_LEVEL.append('none')

In [81]:
len (IB_MTH_LEVEL)

1791

In [82]:
mth161['IB_MTH_LEVEL'] = IB_MTH_LEVEL

In [83]:
ACT_MTH_LEVEL = []

In [84]:
for row in mth161['ACT']:
    if row <25:
        ACT_MTH_LEVEL.append ('Algebra')
    elif row >=25 and row <27:
        ACT_MTH_LEVEL.append('pre-calc')
    elif row >=28 and row <30:
        ACT_MTH_LEVEL.append ('pre-calc 130,108,140')
    elif row >=31:
        ACT_MTH_LEVEL.append('MTH161 ready')
    else:
         ACT_MTH_LEVEL.append('none')

In [85]:
len (ACT_MTH_LEVEL)

1791

In [86]:
mth161['ACT_MTH_LEVEL'] = ACT_MTH_LEVEL

In [88]:
SAT_MSS_LEVEL = []

In [90]:
for row in mth161['ACT']:
    if row <600:
        SAT_MSS_LEVEL.append ('Algebra')
    elif row >=600 and row <640:
        SAT_MSS_LEVEL.append('pre-calc')
    elif row >=650 and row <720:
        SAT_MSS_LEVEL.append ('pre-calc 130,108,140')
    elif row >=730:
        SAT_MSS_LEVEL.append('MTH161 ready')
    else:
         SAT_MSS_LEVEL.append('none')

In [91]:
len (SAT_MSS_LEVEL)

1791

In [92]:
mth161['SAT_MSS_LEVEL'] = SAT_MSS_LEVEL

In [93]:
mth161.head(5)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,AP_MTH_LEVEL,IB_MTH_LEVEL,ACT_MTH_LEVEL,SAT_MSS_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,error,none,Algebra,Algebra
1,50457667,84,0,0,0,0,0,0,MTH161 ready,error,none,Algebra,Algebra
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,error,none,Algebra,Algebra
3,50480064,63,0,0,0,0,0,0,pre-calc,error,none,Algebra,Algebra
4,50480105,65,0,0,MTH 101,0,0,0,"pre-calc 130,108,140",error,none,Algebra,Algebra

In [95]:
del mth161['AP_MTH_LEVEL']
del mth161['IB_MTH_LEVEL']
del mth161['ACT_MTH_LEVEL']
del mth161['SAT_MSS_LEVEL']

mth161.head(5)

In [96]:
mth161.head(5)

         ID  ALKS AP  IB   COURSE  ACT  MSS  MTH        ALKS_MTH_LEVEL
0  50432885    89  0   0        0    0    0    0          MTH161 ready
1  50457667    84  0   0        0    0    0    0          MTH161 ready
2  50475188     0  0   0  MTH 101    0    0  600               Algebra
3  50480064    63  0   0        0    0    0    0              pre-calc
4  50480105    65  0   0  MTH 101    0    0    0  pre-calc 130,108,140

In [98]:
ACT_LEVEL = []

In [99]:
for row in mth161['ACT']:
    if row <25:
        ACT_LEVEL.append ('Algebra')
    elif row >=25 and row <27:
        ACT_LEVEL.append('pre-calc')
    elif row >=28 and row <30:
        ACT_LEVEL.append ('pre-calc 130,108,140')
    elif row >=31:
        ACT_LEVEL.append('MTH161 ready')
    else:
         ACT_LEVEL.append('none')

mth161['ACT_LEVEL'] = ACT_LEVEL

In [100]:
mth161['ACT_LEVEL'] = ACT_LEVEL

In [101]:
mth161.head(5)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,ACT_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,Algebra
1,50457667,84,0,0,0,0,0,0,MTH161 ready,Algebra
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,Algebra
3,50480064,63,0,0,0,0,0,0,pre-calc,Algebra
4,50480105,65,0,0,MTH 101,0,0,0,"pre-calc 130,108,140",Algebra

In [102]:
ACT_LEVEL

['Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'none',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'Algebra',
 'pre-calc',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'none',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'none',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'none',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 'Algebra',
 ...]

In [103]:
ACT2_LEVEL = []

In [104]:
for row in mth161['ACT']:
    if row >1 and row <25:
        ACT2_LEVEL.append ('Algebra')
    elif row >=25 and row <27:
        ACT2_LEVEL.append('pre-calc')
    elif row >=28 and row <30:
        ACT2_LEVEL.append ('pre-calc 130,108,140')
    elif row >=31:
        ACT2_LEVEL.append('MTH161 ready')
    else:
         ACT2_LEVEL.append('none')

In [105]:
mth161['ACT2_LEVEL'] = ACT2_LEVEL

In [106]:
mth161.head(14)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,ACT_LEVEL,ACT2_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,Algebra,none
1,50457667,84,0,0,0,0,0,0,MTH161 ready,Algebra,none
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,Algebra,none
3,50480064,63,0,0,0,0,0,0,pre-calc,Algebra,none
4,50480105,65,0,0,MTH 101,0,0,0,"pre-calc 130,108,140",Algebra,none
5,50480115,73,0,0,0,0,0,0,"pre-calc 130,108,140",Algebra,none
6,50480127,65,0,0,0,0,0,0,"pre-calc 130,108,140",Algebra,none
7,54000209,81,0,0,0,0,0,0,MTH161 ready,Algebra,none
8,54000751,90,MAB 5,0,0,0,0,0,MTH161 ready,Algebra,none
9,53673491,55,0,0,0,0,0,0,pre-calc,Algebra,none
10,54001161,67,0,0,0,0,0,0,"pre-calc 130,108,140",Algebra,none
11,54005970,87,0,0,MTH 101,0,0,0,MTH161 ready,Algebra,none
12,53762062,79,0,0,0,0,0,0,MTH161 ready,Algebra,none
13,54006062,81,0,0,0,0,0,0,MTH161 ready,Algebra,none

In [108]:
del mth161['ACT_LEVEL']

In [109]:
mth161.head(3)

         ID  ALKS AP  IB   COURSE  ACT  MSS  MTH ALKS_MTH_LEVEL ACT2_LEVEL
0  50432885    89  0   0        0    0    0    0   MTH161 ready       none
1  50457667    84  0   0        0    0    0    0   MTH161 ready       none
2  50475188     0  0   0  MTH 101    0    0  600        Algebra       none

In [110]:
CRSE_LEVEL = []

In [111]:
for row in mth161['COURSE']:
    if row == 'MTH 099':
        CRSE_LEVEL.append ('Algebra')
    elif row == 'MTH 101':
        CRSE_LEVEL.append('pre-calc')
    elif row == 'MTH 107' or row == 'MTH 105' or row == 'MTH 113':
        CRSE_LEVEL.append ('pre-calc 130,108,140')
    elif row == 'MTH 130' or row == 'MTH 108' or row == 'MTH 140':
        CRSE_LEVEL.append('MTH161 ready')
    else:
         CRSE_LEVEL.append('none')

In [112]:
mth161 ['CRSE_LEVEL'] = CRSE_LEVEL

In [113]:
mth161.head(5)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,ACT2_LEVEL,CRSE_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,none,none
1,50457667,84,0,0,0,0,0,0,MTH161 ready,none,none
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,none,pre-calc
3,50480064,63,0,0,0,0,0,0,pre-calc,none,none
4,50480105,65,0,0,MTH 101,0,0,0,"pre-calc 130,108,140",none,pre-calc

In [114]:
MSS_LEVEL = []

In [115]:
for row in mth161['MSS']:
    if row >0 and row < 600:
        MSS_LEVEL.append ('Algebra')
    elif row >= 600 and row < 640:
        MSS_LEVEL.append('pre-calc')
    elif row >= 650 and row <720:
        MSS_LEVEL.append ('pre-calc 130,108,140')
    elif row >= 730:
        MSS_LEVEL.append('MTH161 ready')
    else:
         MSS_LEVEL.append('none')

In [116]:
len (MSS_LEVEL)

1791

In [117]:
mth161 ['MSS_LEVEL'] = MSS_LEVEL

In [118]:
mth161.head(4)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,ACT2_LEVEL,CRSE_LEVEL,MSS_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,none,none,none
1,50457667,84,0,0,0,0,0,0,MTH161 ready,none,none,none
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,none,pre-calc,none
3,50480064,63,0,0,0,0,0,0,pre-calc,none,none,none

In [119]:
SATMTH_LEVEL = []

In [120]:
for row in mth161['MTH']:
    if row >0 and row < 580:
        SATMTH_LEVEL.append ('Algebra')
    elif row >= 580 and row < 620:
        SATMTH_LEVEL.append('pre-calc')
    elif row >= 630 and row <790:
        SATMTH_LEVEL.append ('pre-calc 130,108,140')
    elif row >= 700:
        SATMTH_LEVEL.append('MTH161 ready')
    else:
         SATMTH_LEVEL.append('none')

In [121]:
mth161 ['SATMTH_LEVEL'] = SATMTH_LEVEL

In [122]:
mth161.head(4)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,ACT2_LEVEL,CRSE_LEVEL,MSS_LEVEL,SATMTH_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,none,none,none,none
1,50457667,84,0,0,0,0,0,0,MTH161 ready,none,none,none,none
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,none,pre-calc,none,pre-calc
3,50480064,63,0,0,0,0,0,0,pre-calc,none,none,none,none

In [123]:
AP_LEVEL = []

In [124]:
for row in mth161['AP']:
    if row == "MAB 3":
        AP_LEVEL.append ('pre-calc 130,108,140')
    elif row == 'MAB 4 ' or row == 'MAB 5':
        AP_LEVEL.append ('MTH161 ready')
    elif row == 'MBC 4' or row == 'MBC 5' or row == 'MBC 6':
        AP_LEVEL.append ('MTH161 ready')
    else:
        AP_LEVEL.append('none')

In [126]:
IB_LEVEL = []

In [127]:
for row in mth161['IB']:
    if row >= 4:
        IB_LEVEL.append ('MTH161 ready')
    else:
        IB_LEVEL.append('none')

In [128]:
mth161['AP_LEVEL'] = AP_LEVEL
mth161['IB_LEVEL'] = IB_LEVEL

In [129]:
mth161.head(4)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ALKS_MTH_LEVEL,ACT2_LEVEL,CRSE_LEVEL,MSS_LEVEL,SATMTH_LEVEL,AP_LEVEL,IB_LEVEL
0,50432885,89,0,0,0,0,0,0,MTH161 ready,none,none,none,none,none,none
1,50457667,84,0,0,0,0,0,0,MTH161 ready,none,none,none,none,none,none
2,50475188,0,0,0,MTH 101,0,0,600,Algebra,none,pre-calc,none,pre-calc,none,none
3,50480064,63,0,0,0,0,0,0,pre-calc,none,none,none,none,none,none

In [130]:
ALEK_MATH_LEVEL = []

In [131]:
for row in mth161['ALKS']:
    if row > 0 and row <55:
        ALEK_MATH_LEVEL.append ('Algebra')
    elif row >=55:
        ALEK_MATH_LEVEL.append('pre-calc')
    elif row >=65:
        ALEK_MATH_LEVEL.append ('pre-calc 130,108,140')
    elif row >=75:
        ALEK_MATH_LEVEL.append('MTH161 ready')
    else:
        ALEK_MATH_LEVEL.append('none')

In [132]:
mth161['ALEK_MATH_LEVEL'] =ALEK_MATH_LEVEL

In [133]:
del mth161['ALKS_MTH_LEVEL']

In [134]:
mth161.head(4)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ACT2_LEVEL,CRSE_LEVEL,MSS_LEVEL,SATMTH_LEVEL,AP_LEVEL,IB_LEVEL,ALEK_MATH_LEVEL
0,50432885,89,0,0,0,0,0,0,none,none,none,none,none,none,pre-calc
1,50457667,84,0,0,0,0,0,0,none,none,none,none,none,none,pre-calc
2,50475188,0,0,0,MTH 101,0,0,600,none,pre-calc,none,pre-calc,none,none,none
3,50480064,63,0,0,0,0,0,0,none,none,none,none,none,none,pre-calc

In [141]:
 ALEK2_MATH_LEVEL = []

In [142]:
for row in mth161['ALKS']:
    if row > 0 and row <55:
        ALEK2_MATH_LEVEL.append ('Algebra')
    elif row >=55 and row <65:
        ALEK2_MATH_LEVEL.append('pre-calc')
    elif row >=65 and row < 75:
        ALEK2_MATH_LEVEL.append ('pre-calc 130,108,140')
    elif row >=75:
        ALEK2_MATH_LEVEL.append('MTH161 ready')
    else:
        ALEK2_MATH_LEVEL.append('none')

In [144]:
ALEK2_MATH_LEVEL

['MTH161 ready',
 'MTH161 ready',
 'none',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'none',
 'none',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'none',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'pre-calc 130,108,140',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'MTH161 ready',
 'pre-calc',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'none',
 'pre-calc 130,108,140',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'none',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'none',
 'MTH161 ready',
 'none',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'none',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'none',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'none',
 'none',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'MTH161 ready',
 'none',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'none',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'none',
 'pre-calc',
 'Algebra',
 'none',
 'pre-calc 130,108,140',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'none',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'none',
 'Algebra',
 'none',
 'pre-calc 130,108,140',
 'none',
 'pre-calc',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'pre-calc 130,108,140',
 'none',
 'none',
 'pre-calc',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'none',
 'none',
 'none',
 'none',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'none',
 'none',
 'none',
 'MTH161 ready',
 'none',
 'none',
 'MTH161 ready',
 'none',
 'none',
 'Algebra',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'none',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'none',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'none',
 'none',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'Algebra',
 'MTH161 ready',
 'none',
 'none',
 'none',
 'none',
 'none',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'none',
 'none',
 'none',
 'none',
 'Algebra',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'none',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'none',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'none',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc',
 'pre-calc',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'none',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'Algebra',
 'none',
 'MTH161 ready',
 'Algebra',
 'Algebra',
 'Algebra',
 'MTH161 ready',
 'pre-calc',
 'pre-calc',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'Algebra',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'none',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc',
 'Algebra',
 'Algebra',
 'pre-calc',
 'MTH161 ready',
 'MTH161 ready',
 'pre-calc 130,108,140',
 'MTH161 ready',
 'MTH161 ready',
 'Algebra',
 'MTH161 ready',
 ...]

In [145]:
del mth161['ALEK_MATH_LEVEL']

In [146]:
mth161['ALEK2_MATH_LEVEL'] = ALEK2_MATH_LEVEL

In [147]:
mth161.head(4)

,ID,ALKS,AP,IB,COURSE,ACT,MSS,MTH,ACT2_LEVEL,CRSE_LEVEL,MSS_LEVEL,SATMTH_LEVEL,AP_LEVEL,IB_LEVEL,ALEK2_MATH_LEVEL
0,50432885,89,0,0,0,0,0,0,none,none,none,none,none,none,MTH161 ready
1,50457667,84,0,0,0,0,0,0,none,none,none,none,none,none,MTH161 ready
2,50475188,0,0,0,MTH 101,0,0,600,none,pre-calc,none,pre-calc,none,none,none
3,50480064,63,0,0,0,0,0,0,none,none,none,none,none,none,pre-calc

In [149]:
from IPython.display import FileLink, FileLinks

In [153]:
FileLink('/notebooks/TEST%20Py/mth161.py')

C:\notebooks\TEST%20Py\mth161.py